### ISSUE TITLE
KeyError: 'name' 

### ISSUE THREAD

**Issue by JusSil501** [johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial#10]
![image](https://user-images.githubusercontent.com/94770319/181069036-cd92ca16-168a-42e4-8b67-1e9727cfc288.png)

It seems that a learning_rate scheduler is not found? Don t understand the issue?

**Comment by johschmidt42** [comment]
May it be possible that you're training with features that require to have a learning_rate scheduler?
Could you show me your training script? @JusSil501

**Comment by johschmidt42** [comment]
Stale
