### ISSUE TITLE
how do I monitor accuracy with the logger ?

### ISSUE THREAD

**Issue by GagahGK** [johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial#2]
Hello first of all thank you for making the article in the Medium 
I wanted to make a custom object detector using the tutorial you provided 
however, I saw that in the medium article the script did not monitor the accuracy (TP+TN)/(TP+TN+FP+FN)
how do I add that metric to the logger? any help would be appreciated

**Comment by johschmidt42** [comment]
In the `FasterRCNN_lightning` class, the validation step returns the predicted and the ground truth boxes: 
```
def validation_step(self, batch, batch_idx):
    
    (...)

    return {"pred_boxes": pred_boxes, "gt_boxes": gt_boxes}
```

Then at the end of the validation epoch, these predicted and gt boxes are used to compute the metrics with the help of the [metrics section](https://github.com/johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial/tree/master/pytorch_faster_rcnn_tutorial/metrics). The values are logged with `self.log`.
```
def validation_epoch_end(self, outs):
    gt_boxes = [out["gt_boxes"] for out in outs]
    gt_boxes = list(chain(*gt_boxes))
    pred_boxes = [out["pred_boxes"] for out in outs]
    pred_boxes = list(chain(*pred_boxes))

    metric = get_pascalvoc_metrics(
        gt_boxes=gt_boxes,
        det_boxes=pred_boxes,
        iou_threshold=self.iou_threshold,
        method=MethodAveragePrecision.EVERY_POINT_INTERPOLATION,
        generate_table=True,
    )

    per_class, mAP = metric["per_class"], metric["mAP"]
    self.log("Validation_mAP", mAP)

    for key, value in per_class.items():
        self.log(f"Validation_AP_{key}", value["AP"])
```

If you want to add accuracy, you can do it here. You just need to define what a TP, FP, TN, FP would be in your case. For object detection, you might want to use a suitable evalutation metric like average precision.

**Comment by johschmidt42** [comment]
To evaluate the performance of an object detection algorithm, detection evaluation metrics are used. The most common one is the average precision (AP) or the mean average precision as used in the PASCAL Challenge (Mark Everingham et al. 2010). These measure how close the detected bounding boxes are to the ground truth boxes. The amount of overlap of the predicted and ground truth area is measured to assess the performance for each class independently. A perfect match between ground truth and predicted box is given when the area and the location are the same. These two conditions can be measured with the intersection of union (IoU) metric. This metric is based on the Jaccard Index, a similarity coefficient between two sets of data. A good object detector should find all ground truth boxes (high recall) while at the same time only identifying relevant objects (high precision). The average precision (AP) is a suitable met-ric based on the area under a precision x recall curve that takes the confidence levels of predic-tions into account. In other words, AP penalizes when the detector misses a box that should have been detected, as well as when it detects something that does not exist or detect the same thing multiple times. A more comprehensive explanation of the IoU and the AP evaluation metric is given in (Padilla et al. 2021).

**Comment by GagahGK** [comment]
Hello, thank you for replying to the issue and explaining how to do it, for now, I'm just going to close the issue and come back when I have implemented the custom evaluation metric later.
