### ISSUE TITLE
ValueError: Could not find a format to read the specified file in single-image mode

### ISSUE THREAD

**Issue by shubhamgajrani** [johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial#3]
I tried to implement FASTER RCNN using PyTorch, but I'm consistently getting same error for all the viewers(datasets viewer/anchorviewer). I tried to add plugin = "imread" to read_images function, but error still remains.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/_n/drkfc7xj0_b5jpq4c8c19f240000gn/T/ipykernel_3698/1313361764.py in <module>
      1 from pytorch_faster_rcnn_tutorial.visual import AnchorViewer
----> 2 image = dataset[0]['x']
      3 feature_map_size = (512, 32, 32)
      4 anchorviewer = AnchorViewer(image=image,
      5                             rcnn_transform=transform,

~/Documents/PhD Data/Machine learning/September 2021/PyTorch-Object-Detection-Faster-RCNN-Tutorial/pytorch_faster_rcnn_tutorial/datasets.py in __getitem__(self, index)
     57 
     58             # Load input and target
---> 59             x, y = self.read_images(input_ID, target_ID)
     60 
     61         # From RGBA to RGB

~/Documents/PhD Data/Machine learning/September 2021/PyTorch-Object-Detection-Faster-RCNN-Tutorial/pytorch_faster_rcnn_tutorial/datasets.py in read_images(inp, tar)
    128     @staticmethod
    129     def read_images(inp, tar):
--> 130         return imread(inp), read_json(tar)
    131 
    132 

~/opt/anaconda3/envs/napari-env/lib/python3.9/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, **plugin_args)
     46 
     47     with file_or_url_context(fname) as fname:
---> 48         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     49 
     50     if not hasattr(img, 'ndim'):

~/opt/anaconda3/envs/napari-env/lib/python3.9/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    205                                (plugin, kind))
    206 
--> 207     return func(*args, **kwargs)
    208 
    209 

~/opt/anaconda3/envs/napari-env/lib/python3.9/site-packages/skimage/io/_plugins/imageio_plugin.py in imread(*args, **kwargs)
      8 @wraps(imageio_imread)
      9 def imread(*args, **kwargs):
---> 10     return np.asarray(imageio_imread(*args, **kwargs))

~/opt/anaconda3/envs/napari-env/lib/python3.9/site-packages/imageio/core/functions.py in imread(uri, format, **kwargs)
    263 
    264     # Get reader and read first
--> 265     reader = read(uri, format, "i", **kwargs)
    266     with reader:
    267         return reader.get_data(0)

~/opt/anaconda3/envs/napari-env/lib/python3.9/site-packages/imageio/core/functions.py in get_reader(uri, format, mode, **kwargs)
    179     if format is None:
    180         modename = MODENAMES.get(mode, mode)
--> 181         raise ValueError(
    182             "Could not find a format to read the specified file in %s mode" % modename
    183         )

ValueError: Could not find a format to read the specified file in single-image mode

**Comment by johschmidt42** [comment]
`skimage.io.imread` seems not be able to read your images. Could you provide some more information about your images?

**Comment by johschmidt42** [comment]
FYI: All viewers use the dataset class, which in turn reads the images using `skimage.io.imread`.

**Comment by shubhamgajrani** [comment]
> `skimage.io.imread` seems not be able to read your images. Could you provide some more information about your images?

Hi, my images are RBG images in format .Png

**Comment by johschmidt42** [comment]
If that's the case, there shouldn't be any problems reading them. Would you mind sharing one image with me through email or LinkedIn?
Also could you check your package version of skimage?

**Comment by shubhamgajrani** [comment]
skimage version is 0.18.3.
Could you please provide your email?

**Comment by shubhamgajrani** [comment]
I think the error arises due to indexing differences in skimage and ObjectDetectionDataSet(torch.utils.data.Dataset) class, since in datasets, index 1 to n gives an output ( sample = dataset[0] gives the same error).

In training script, I made the changes : 
# training validation test split
inputs_train, inputs_valid, inputs_test = inputs[1:40], inputs[40:54], inputs[54:]
targets_train, targets_valid, targets_test = targets[1:40], targets[40:54], targets[54:]

and now I don't get this error!
Thanks!

**Comment by johschmidt42** [comment]
Not so sure this is an indexing issue but rather the image at index 0 can't be read with `skimage.io.imread`.
Maybe the image itself is corrupted or has untypical dimensions?
All the dataset does is to store a list of paths (images and targets) and then when you call the `_ _getitem__` method by using the square bracket on the dataset object, like dataset[0], it will execute the code where `imread` is used.

**Comment by shubhamgajrani** [comment]
I changed the image at index 0, which previously was read at index 1 - leading to the same error.
Moreover, I had 68 images, and dataset[68] gave an output of correct values.

**Comment by johschmidt42** [comment]
`self.inputs` and `self.targets` are of type `List[str]`

```python
def __getitem__(self, index: int):
            # Select the sample
            input_ID = self.inputs[index]
            target_ID = self.targets[index]

            # Load input and target
            x, y = self.read_images(input_ID, target_ID)

@staticmethod
def read_images(inp, tar):
    return imread(inp), read_json(tar)
```

So `dataset[0]` will call `__getitem__(index=0)` which in turn reads the image and target at position 0 from the provided lists `inputs` and `targets`.

My guess still is that there seems to be something wrong with your `inputs` list.
Because there is no need to start at 1 if you have a valid list (python indexing starts at 0).
Also, if you have 68 images, then you can't do something like `dataset[68]`. The maximum is ofc `dataset[67]`

Could you print your inputs when you do:
```python
inputs = get_filenames_of_path(some_path)
```
