### ISSUE TITLE
error: UnpicklingError: invalid load key, '{'.

### ISSUE THREAD

**Issue by JusSil501** [johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial#8]
I get this error when trying to load in the annotated file of my first image. I was using the annotator.export function to save the annotated file to my image path. Any ideas to fix this
![Capture](https://user-images.githubusercontent.com/94770319/180356612-34e2f4db-972b-45bd-9118-f0a87fa8bade.JPG)

This is the json file of that pickled image
![432fdzhgz](https://user-images.githubusercontent.com/94770319/180356962-bc4c61e3-1dd5-4555-b02c-70eb9a1a7dd9.JPG)

**Comment by johschmidt42** [comment]
Hey, it looks like you're trying to open a `json` file with `torch.load()`. This function uses the [pickle module under the hood](https://pytorch.org/docs/stable/generated/torch.load.html). Since you don't have a pickled file, try to open it using the `json` module: 
```python
with open(file=filepath, mode="r") as file_handle:
    data: dict = json.load(file_handle)
```

**Comment by JusSil501** [comment]
> Hey, it looks like you're trying to open a `json` file with `torch.load()`. This function uses the [pickle module under the hood](https://pytorch.org/docs/stable/generated/torch.load.html). Since you don't have a pickled file, try to open it using the `json` module:
> 
> ```python
> with open(file=filepath, mode="r") as file_handle:
>     data: dict = json.load(file_handle)
> ```
> 
> For the napari viewer, I also read in the annotation data with the `json` module: https://github.com/johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial/blob/cec177e047813fe3db17896180d3580453170469/pytorch_faster_rcnn_tutorial/utils.py#L29:~:text=def%20read_json(,return%20file)
> 
> Here's a little tutorial for working with json in python: [Working With JSON Data in Python](https://realpython.com/python-json/)

Ok, how are you able to use torch.load if it only expects pickled files. How should I go about changing annotated files into the tensors?

**Comment by johschmidt42** [comment]
@JusSil501  What is you goal exactly? If you want to transform your json files (annotations) into torch tensors and e.g. use these for training,[ this is how you can do it](https://github.com/johschmidt42/PyTorch-Object-Detection-Faster-RCNN-Tutorial/blob/master/pytorch_faster_rcnn_tutorial/datasets.py#:~:text=(x)-,%23%20Read%20boxes,-try%3A).

**Comment by johschmidt42** [comment]
@JusSil501 Let me know if that helped you.

**Comment by JusSil501** [comment]
> @JusSil501 Let me know if that helped you.

Im good thanks!
